import Link from "next/link";
import { articles, categories, projects, trending } from "./data";
import type { Article, Project } from "./types";

export function Footer() { return <footer className="footer"><div className="wrap footer-top"><Link href="/" className="brand footer-brand"><span className="brand-mark">CR</span><span className="brand-name">CONSTRUCTION<br/>REVIEW</span></Link><p>Built with structure.<br/>Presented with clarity.</p><div className="footer-links"><Link href="/about">About</Link><Link href="/companies">Companies</Link><Link href="/projects">Projects</Link><Link href="/search">Search</Link></div></div><div className="wrap footer-bottom"><span>© 2026 Construction Review. A static editorial demo.</span><span>Construction intelligence, clearly presented.</span></div></footer>; }

export function SectionHeading({ eyebrow, title, link, href }: { eyebrow: string; title: string; link?: string; href?: string }) { return <div className="section-heading"><div><div className="eyebrow">{eyebrow}</div><h2>{title}</h2></div>{link && href && <Link className="text-link" href={href}>{link}<span>↗</span></Link>}</div>; }

export function ArticleCard({ article, variant = "standard" }: { article: Article; variant?: "standard" | "compact" }) { return <article className={`article-card ${variant}`}><Link href={`/article/${article.slug}`} className="article-image image-link" style={{ backgroundImage: `url('${article.image}')` }} aria-label={article.title}><span className="image-arrow">↗</span></Link><div className="article-meta"><span>{article.category}</span><span>{article.readTime} min read</span></div><h3><Link href={`/article/${article.slug}`}>{article.title}</Link></h3><p>{article.excerpt}</p><div className="article-date">{article.date}</div></article>; }

export function ProjectCard({ project, featured = false }: { project: Project; featured?: boolean }) { return <article className={`project-card ${featured ? "project-featured" : ""}`}><Link href={`/projects/${project.slug}`} className="project-image image-link" style={{ backgroundImage: `url('${project.image}')` }} aria-label={project.title}><span className="demo-tag">DEMO PROJECT</span><span className="image-arrow">↗</span></Link><div className="project-card-copy"><div className="eyebrow">{project.sector} <span className="dot">/</span> {project.country}</div><h3><Link href={`/projects/${project.slug}`}>{project.title}</Link></h3><p>{project.description}</p><div className="project-stats"><div><span>LOCATION</span><strong>{project.location}, {project.country}</strong></div><div><span>PROJECT VALUE</span><strong>{project.value}</strong></div><div><span>STATUS</span><strong>{project.status}</strong></div></div></div></article>; }

export function Newsletter() { return <section className="newsletter" id="newsletter"><div className="wrap newsletter-inner"><div><div className="eyebrow">A considered weekly briefing</div><h2>THE WEEK IN<br/><span>CONSTRUCTION</span></h2><p>The projects, companies and industry developments worth knowing.</p></div><form className="newsletter-form"><label htmlFor="email">Get the editorial briefing in your inbox.</label><div className="email-row"><input id="email" type="email" placeholder="Your email address"/><button type="button">JOIN <span>↗</span></button></div><small>Static demo. No email is collected or stored.</small></form></div></section>; }

export function ListingPage({ kind }: { kind: "news" | "know-how" | "materials" }) { const config = { news: { title: "NEWS / THE LATEST", desc: "Reporting and perspectives on the projects, people and forces shaping construction.", filter: () => true }, "know-how": { title: "KNOW-HOW / FIELD NOTES", desc: "Practical knowledge for understanding how the built world comes together.", filter: (article: Article) => article.category === "Know-how" }, materials: { title: "MATERIALS / INSTALLATIONS", desc: "Products, systems and technologies shaping the built environment.", filter: (article: Article) => article.category === "Materials" } }[kind]; const entries = articles.filter(config.filter); return <main><div className="page-intro wrap"><div className="eyebrow">Construction Review / Journal</div><h1>{config.title}</h1><p>{config.desc}</p></div><div className="wrap listing-layout"><div className="listing-grid">{entries.map(item => <ArticleCard key={item.id} article={item}/>)}</div><aside className="trending-side"><div className="eyebrow">Most read</div><Trending/></aside></div></main>; }

export function Trending() { return <ol className="trending-list">{trending.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><Link href="/know-how">{item}<b>↗</b></Link></li>)}</ol>; }

export function ArticleDetail({ article }: { article: Article }) { return <main className="detail-page"><div className="wrap"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/news">News</Link><span>/</span><span>{article.category}</span></div><div className="article-detail-head"><div className="eyebrow">{article.category} <span className="dot">/</span> {article.date} <span className="dot">/</span> {article.readTime} min read</div><h1>{article.title}</h1><p>{article.excerpt}</p><div className="byline">Words by <strong>{article.author}</strong></div></div><div className="detail-image" style={{ backgroundImage: `url('${article.image}')` }}/><div className="article-body">{article.body.map((paragraph, i) => <p key={i}>{paragraph}</p>)}<p className="demo-note">Construction Review editorial demo content.</p></div><section className="related-section"><SectionHeading eyebrow="Continue reading" title="More from the journal"/><div className="article-grid">{articles.filter(item => item.id !== article.id).slice(0, 3).map(item => <ArticleCard key={item.id} article={item}/>)}</div></section></div></main>; }

export function ProjectsPage() { return <main><div className="page-intro wrap"><div className="eyebrow">Project intelligence / Africa</div><h1>PROJECTS /<br/>AFRICA’S BUILT FUTURE</h1><p>A closer view of the ambitious projects shaping the continent. Every project shown here is fictional demo content.</p></div><section className="wrap projects-list"><ProjectCard project={projects[0]} featured/><div className="project-grid">{projects.slice(1).map(project => <ProjectCard key={project.id} project={project}/>)}</div></section></main>; }

export function ProjectDetail({ project }: { project: Project }) { return <main className="detail-page"><div className="wrap"><div className="breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/projects">Projects</Link><span>/</span><span>{project.country}</span></div><div className="project-detail-head"><div className="eyebrow">{project.sector} <span className="dot">/</span> {project.location}, {project.country} <span className="dot">/</span> Demo profile</div><h1>{project.title}</h1><p>{project.description}</p></div><div className="detail-image project-detail-image" style={{ backgroundImage: `url('${project.image}')` }}/><div className="demo-disclaimer">DEMO PROFILE <span>All project information on this page is fictional and illustrative.</span></div><div className="project-facts">{[["STATUS", project.status], ["PROJECT VALUE", project.value], ["COMPLETION", String(project.completionYear)], ["DEVELOPER", project.developer], ["CONTRACTOR", project.contractor], ["LATEST UPDATE", project.lastUpdated]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="project-overview"><div className="eyebrow">Project overview</div><h2>A regional vision,<br/>built for what comes next.</h2><div><p>{project.overview}</p><p>Profiles are structured to support clear, comparable project intelligence as the publication evolves.</p></div></div><section className="related-section"><SectionHeading eyebrow="On the ground" title="Related stories" link="All news" href="/news"/><div className="article-grid">{articles.slice(0, 3).map(item => <ArticleCard key={item.id} article={item}/>)}</div></section></div></main>; }

export function CompanyPage() { return <main><div className="page-intro wrap"><div className="eyebrow">Industry directory / Demo profile</div><h1>COMPANIES /<br/>WHO BUILDS WHAT’S NEXT</h1><p>A future-ready directory for the people and organisations shaping the built environment.</p></div><div className="wrap company-feature"><div className="company-image" style={{ backgroundImage: `url('${categories[1].image}')` }}/><div className="company-copy"><div className="eyebrow">Company spotlight / Demo listing</div><h2>Example Construction Group</h2><div className="company-location">Infrastructure <span>·</span> Nairobi, Kenya</div><p>Example Construction Group is fictional directory content created to demonstrate a professional company profile within Construction Review.</p><Link className="text-link" href="/about">VIEW PROFILE <span>↗</span></Link></div></div></main>; }

export function SearchPage({ query = "" }: { query?: string }) { const term = query.trim().toLowerCase(); const storyMatches = term ? articles.filter(item => `${item.title} ${item.category} ${item.excerpt}`.toLowerCase().includes(term)) : []; const projectMatches = term ? projects.filter(item => `${item.title} ${item.sector} ${item.location} ${item.country}`.toLowerCase().includes(term)) : []; return <main><div className="page-intro wrap"><div className="eyebrow">Explore the journal</div><h1>SEARCH /<br/>CONSTRUCTION REVIEW</h1><form action="/search" className="search-form"><label htmlFor="q">Search stories, projects and topics</label><div><input id="q" name="q" defaultValue={query} placeholder="Try infrastructure, materials, energy…"/><button>SEARCH ↗</button></div></form></div>{term && <section className="wrap search-results"><div className="eyebrow">Results for “{query}”</div>{storyMatches.length > 0 && <><h2>Stories</h2><div className="article-grid">{storyMatches.map(item => <ArticleCard key={item.id} article={item}/>)}</div></>}{projectMatches.length > 0 && <><h2>Projects <span className="demo-inline">/ FICTIONAL DEMO PROFILES</span></h2><div className="project-grid">{projectMatches.map(item => <ProjectCard key={item.id} project={item}/>)}</div></>}{storyMatches.length === 0 && projectMatches.length === 0 && <p className="empty-results">No matches found. Try a broader topic such as energy, buildings or Kenya.</p>}</section>}</main>; }
