import type { Article, IndustryCategory, Project } from "./types";

const images = {
  building: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1400&q=85",
  tower: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=85",
  bridge: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1400&q=85",
  interior: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=85",
  road: "https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1400&q=85",
  energy: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1400&q=85",
  materials: "https://images.unsplash.com/photo-1511818966892-d7d671e672a2?auto=format&fit=crop&w=1400&q=85",
  city: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?auto=format&fit=crop&w=1400&q=85",
};

export const articles: Article[] = [
  { id: "a1", slug: "east-africa-rail-investment", title: "East Africa’s next rail chapter moves from blueprint to ground", category: "Infrastructure", excerpt: "A new generation of regional transport links is reshaping how the region plans trade, cities and long-term investment.", date: "27 September 2026", readTime: 6, image: images.bridge, author: "Editorial Desk", body: ["Across East Africa, transport planners are revisiting the scale and purpose of the region’s rail network. New corridors are being considered as part of a wider rethink of freight, urban growth and cross-border trade.", "The challenge is not only to deliver new infrastructure, but to connect it thoughtfully to existing cities and communities. Financing, land use and long-term maintenance will shape whether these ambitions become durable public assets."] },
  { id: "a2", slug: "low-carbon-concrete-frontier", title: "The low-carbon concrete frontier is taking shape", category: "Materials", excerpt: "New mix designs and local supply chains are bringing embodied carbon into sharper focus.", date: "26 September 2026", readTime: 4, image: images.materials, author: "Nia Okafor", body: ["Concrete remains foundational to the built environment. Across the industry, researchers and manufacturers are exploring ways to lower its footprint while protecting strength, availability and cost.", "A practical transition depends on regional standards, dependable material testing and procurement that rewards performance over habit."] },
  { id: "a3", slug: "cooling-africas-growing-cities", title: "Cooling Africa’s growing cities without adding to the heat", category: "Energy", excerpt: "Passive design and better systems are becoming central to the region’s building conversation.", date: "25 September 2026", readTime: 5, image: images.building, author: "Daniel Muriuki", body: ["As urban temperatures rise, architects and engineers are rethinking how buildings stay comfortable. Shading, orientation, ventilation and material choices can reduce cooling demand before mechanical systems are specified.", "Efficient HVAC still matters, especially in dense commercial buildings. The strongest results come when design teams coordinate the envelope, controls and maintenance plan from the outset."] },
  { id: "a4", slug: "future-of-modular-building", title: "What modular construction can—and cannot—solve", category: "Construction technology", excerpt: "Factory-led delivery is gaining attention, but the local context still determines the outcome.", date: "24 September 2026", readTime: 7, image: images.tower, author: "Editorial Desk", body: ["Modular construction promises predictable quality and shorter site programmes. Its success depends on early coordination, transport logistics and a supply chain prepared to work to consistent tolerances.", "For markets with evolving standards, close collaboration between regulators, designers and manufacturers is as important as the technology itself."] },
  { id: "a5", slug: "urban-housing-design", title: "Designing the next generation of urban housing", category: "Architecture", excerpt: "A closer look at density, shared space and the everyday life of the city.", date: "23 September 2026", readTime: 5, image: images.city, author: "Amara Njoroge", body: ["Housing quality is shaped by more than unit count. Access to light, shared outdoor space, services and public transport all influence how a neighbourhood works over time.", "Architects and developers are increasingly treating these shared systems as core infrastructure rather than optional extras."] },
  { id: "a6", slug: "construction-machinery-electrification", title: "Can electric machinery work on tomorrow’s sites?", category: "Machinery", excerpt: "Battery equipment is moving beyond pilots as contractors weigh uptime, charging and total cost.", date: "22 September 2026", readTime: 4, image: images.road, author: "Peter Kamau", body: ["Electrification is reaching more categories of construction equipment. The operational case varies by machine, site conditions and access to reliable charging.", "Contractors are evaluating noise, service needs and whole-life costs alongside emissions as they decide where to begin."] },
  { id: "a7", slug: "kenya-road-pricing-guide", title: "Understanding road construction costs in Kenya", category: "Know-how", excerpt: "What influences the cost of a road project, from ground conditions to drainage.", date: "21 September 2026", readTime: 8, image: images.bridge, author: "Editorial Desk", body: ["Road project costs depend on location, ground conditions, design standards and the scope of drainage and structures. Unit prices alone rarely tell the full story.", "Early surveys and transparent specifications help project teams compare proposals on a like-for-like basis."] },
  { id: "a8", slug: "commercial-property-outlook", title: "Commercial property looks beyond the new-build cycle", category: "Real estate", excerpt: "Owners are turning to retrofit, performance and adaptable space to extend asset life.", date: "20 September 2026", readTime: 5, image: images.interior, author: "Lerato Mokoena", body: ["Across commercial real estate, owners are looking at how existing buildings can serve changing tenant needs. Refurbishment and energy performance are central to many asset strategies.", "The next phase of investment may be measured as much by what can be improved as by what can be built from scratch."] },
  { id: "a9", slug: "renewable-power-construction", title: "Renewable power creates a new construction pipeline", category: "Energy", excerpt: "Grid upgrades and generation projects are opening new opportunities for regional contractors.", date: "19 September 2026", readTime: 6, image: images.energy, author: "Editorial Desk", body: ["Renewable generation is creating demand for a broad set of construction capabilities, from civil works to grid connections and specialist installation.", "Long-term project readiness will depend on skilled teams, robust procurement and coordination across energy systems."] },
  { id: "a10", slug: "building-code-materials", title: "Why building codes matter for safer materials", category: "Know-how", excerpt: "Standards connect material performance with safer, more durable buildings.", date: "18 September 2026", readTime: 6, image: images.materials, author: "Nia Okafor", body: ["Building codes translate safety and performance expectations into requirements that designers and builders can apply. For materials, testing and traceability help confirm that specified products perform as intended.", "Clear guidance and accessible technical expertise can make compliance practical across projects of different sizes."] },
  { id: "a11", slug: "construction-talent-africa", title: "Building the skills behind Africa’s construction growth", category: "People", excerpt: "Training and knowledge exchange are critical infrastructure for the sector.", date: "17 September 2026", readTime: 4, image: images.tower, author: "Editorial Desk", body: ["A growing project pipeline calls for a deeper pool of technical and management skills. Employers, training institutions and professional bodies each have a role in building that capacity.", "Practical learning on active projects can help bridge classroom knowledge with the demands of delivery."] },
  { id: "a12", slug: "sustainable-site-practice", title: "Small site decisions with a lasting sustainability impact", category: "Sustainability", excerpt: "Waste, water and procurement choices can add up across a project’s full life.", date: "16 September 2026", readTime: 5, image: images.building, author: "Amara Njoroge", body: ["Project sustainability is often shaped by everyday decisions: how materials are ordered, how water is managed and how waste is separated on site.", "Setting clear responsibilities early makes it easier for teams to track progress and carry good practices through construction."] },
];

export const projects: Project[] = [
  { id: "p1", slug: "nairobi-metro-corridor", title: "Nairobi Metropolitan Transport Corridor", location: "Nairobi", country: "Kenya", sector: "Transport", description: "A fictional regional mobility programme connecting growing urban districts through integrated transit and public realm upgrades.", image: images.bridge, value: "$294M", status: "Under Construction", completionYear: 2026, developer: "MetroLink Development Authority (demo)", contractor: "BuildAxis Consortium (demo)", featured: true, lastUpdated: "Updated 18 September 2026", overview: "This illustrative project profile demonstrates how Construction Review can present project intelligence. The fictional corridor combines transit infrastructure, interchange improvements and safer pedestrian connections across a fast-growing metropolitan area." },
  { id: "p2", slug: "lagos-waterfront-quarter", title: "Lagos Waterfront Quarter", location: "Lagos", country: "Nigeria", sector: "Mixed use", description: "A fictional mixed-use district shaped around public waterfront access and adaptable commercial space.", image: images.city, value: "$186M", status: "In Planning", completionYear: 2028, developer: "Atlantic Works (demo)", contractor: "Northbank Construction (demo)", featured: false, lastUpdated: "Updated 12 September 2026", overview: "A fictional urban regeneration concept pairing commercial buildings with public open space and resilient waterfront infrastructure. All project information is illustrative demo content." },
  { id: "p3", slug: "rift-valley-solar-park", title: "Rift Valley Solar Park", location: "Naivasha", country: "Kenya", sector: "Energy", description: "A fictional utility-scale solar project with grid connection and operations facilities.", image: images.energy, value: "$92M", status: "Pre-construction", completionYear: 2027, developer: "SunGrid Africa (demo)", contractor: "Kifaru Energy Works (demo)", featured: false, lastUpdated: "Updated 08 September 2026", overview: "This fictional project entry illustrates the energy sector profile format. Its stated scope includes a solar array, supporting electrical infrastructure and operations facilities." },
];

export const categories: IndustryCategory[] = [
  { title: "Buildings", description: "Architecture, design and the spaces we inhabit.", image: images.building, href: "/news?category=architecture" },
  { title: "Infrastructure", description: "The systems that connect economies and communities.", image: images.bridge, href: "/projects" },
  { title: "Energy", description: "Powering a more resilient built environment.", image: images.energy, href: "/news?category=energy" },
  { title: "Materials", description: "Products and systems shaping how we build.", image: images.materials, href: "/materials" },
  { title: "Machinery", description: "Equipment, capability and the modern jobsite.", image: images.road, href: "/news?category=machinery" },
  { title: "Technology", description: "Ideas changing how projects are designed and delivered.", image: images.tower, href: "/know-how" },
  { title: "Real Estate", description: "Markets, investment and the future of property.", image: images.interior, href: "/news?category=real-estate" },
];

export const navigation = [
  { label: "News", href: "/news" }, { label: "Projects", href: "/projects" }, { label: "Buildings", href: "/news?category=buildings" }, { label: "Infrastructure", href: "/news?category=infrastructure" }, { label: "Energy", href: "/news?category=energy" }, { label: "Materials", href: "/materials" }, { label: "Machinery", href: "/news?category=machinery" }, { label: "Know-How", href: "/know-how" },
];

export const trending = ["Building Code Requirements for Tempered Glass", "Prices of D8 D10 D12 D16 in Kenya", "Road Construction Stages", "What is Fenestration?", "Construction Tools You Need"];
