import Link from "next/link";
import { articles, categories, projects, trending } from "../data";
import { ArticleCard, ProjectCard, SectionHeading, Newsletter } from "../components";

export default function Home() {
  return <main>
    <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span className="signal"/> Construction intelligence / Vol. 02</div><h1>THE BUILT<br/>WORLD IS <em>MOVING.</em></h1><p>Construction intelligence, projects, people and technologies shaping Africa and the world.</p><Link href="/news" className="primary-link">EXPLORE STORIES <span>↗</span></Link><div className="hero-foot"><span>INDEPENDENT PERSPECTIVES</span><span>AFRICA / INTERNATIONAL</span></div></div><Link href={`/article/${articles[0].slug}`} className="hero-image" style={{ backgroundImage: `url('${articles[0].image}')` }}><span className="image-kicker">THE BIG STORY <span>↗</span></span><span className="hero-story"><span>{articles[0].category} <i>·</i> 6 MIN READ</span><strong>{articles[0].title}</strong><small>{articles[0].excerpt}</small></span><span className="hero-image-index">01 / 04</span></Link></section>
    <section className="wrap featured-section"><SectionHeading eyebrow="The current edition / 01" title="Stories moving the industry" link="View all stories" href="/news"/><div className="featured-grid"><Link href={`/article/${articles[1].slug}`} className="feature-lead"><span className="feature-image" style={{ backgroundImage: `url('${articles[1].image}')` }}/><div className="article-meta"><span>{articles[1].category}</span><span>{articles[1].date}</span></div><h3>{articles[1].title}</h3><p>{articles[1].excerpt}</p><span className="text-link">READ THE STORY <span>↗</span></span></Link><div className="featured-secondary">{articles.slice(2, 5).map((article, i) => <Link className="secondary-story" key={article.id} href={`/article/${article.slug}`}><span className="secondary-index">0{i + 1}</span><span className="secondary-copy"><span className="eyebrow">{article.category}</span><strong>{article.title}</strong><small>{article.date} <i>·</i> {article.readTime} min</small></span><span className="story-arrow">↗</span></Link>)}</div></div></section>
    <section className="latest-section"><div className="wrap"><SectionHeading eyebrow="The journal / Daily reporting" title="Latest stories" link="All news" href="/news"/><div className="article-grid">{articles.slice(3, 9).map(article => <ArticleCard key={article.id} article={article}/>)}</div></div></section>
    <section className="projects-section wrap"><SectionHeading eyebrow="Project intelligence / Africa" title="PROJECTS / AFRICA’S BUILT FUTURE" link="Explore projects" href="/projects"/><p className="section-deck">A closer view of the ambitious projects shaping the continent. <span>All projects shown are fictional demo profiles.</span></p><ProjectCard project={projects[0]} featured/><div className="project-grid home-project-grid">{projects.slice(1).map(project => <ProjectCard key={project.id} project={project}/>)}</div></section>
    <section className="categories-section"><div className="wrap"><SectionHeading eyebrow="Sectors / Systems / People" title="Explore the industry" link="Browse the journal" href="/news"/><div className="category-grid">{categories.map((category, i) => <Link href={category.href} className="category-tile" key={category.title}><span className="category-bg" style={{ backgroundImage: `url('${category.image}')` }}/><span className="category-number">0{i + 1}</span><span className="category-copy"><strong>{category.title}</strong><small>{category.description}</small></span><span className="category-arrow">↗</span></Link>)}</div></div></section>
    <section className="trending-section wrap"><div><div className="eyebrow">The reading list / This week</div><h2>What the industry<br/>is looking for.</h2><p>Questions, topics and practical guidance readers are exploring now.</p></div><ol className="trending-list">{trending.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, "0")}</span><Link href="/know-how">{item}<b>↗</b></Link></li>)}</ol></section>
    <section className="company-spotlight"><div className="wrap spotlight-inner"><div className="spotlight-image" style={{ backgroundImage: `url('${categories[1].image}')` }}><span>DIRECTORY / DEMO</span></div><div className="spotlight-copy"><div className="eyebrow">Company spotlight / Demo listing</div><h2>Example Construction Group</h2><div className="company-location">Infrastructure <span>·</span> Nairobi, Kenya</div><p>Fictional company content demonstrating a future-ready directory for the organisations shaping the built environment.</p><Link className="text-link" href="/companies">VIEW PROFILE <span>↗</span></Link></div><div className="spotlight-number">01<span> / 12</span></div></div></section>
    <Newsletter/>
  </main>;
}
